### ISSUE TITLE
Failing to create beans and Decode argument cannot be null

### ISSUE THREAD

**Issue by omudzingwa** [JianChoi-Kor/Login#1]
Hi. I have followed your project and tried to create my own almost copying everthing that you did but however I am facing some compile to issues, and I have shared my code on the Github Link: https://github.com/omudzingwa/spring-security-jwt-redis-login-logout-demo

I don't know where the problem is. My email is obemudzingwa@gmail.com. Kindly assist.

Thanks.

**Comment by JianChoi-Kor** [comment]
Hi. I saw your code. And I think If you change @AllArgsConstructor
-> @RequiredArgsConstructor in 'AuthFilter class' then the bean will be
created normally.
If you read the mail, can you try it and let me know the result??

2024년 2월 15일 (목) 오후 7:11, omudzingwa ***@***.***>님이 작성:

**Comment by omudzingwa** [comment]
Hi. I have been able to find a fix and the program compliles by simply
changing: SecretKey secretKey =
Keys.hmacShaKeyFor(Decoders.BASE64URL.decode(secret)); to SecretKey
secretKey = Keys.secretKeyFor(SignatureAlgorithm.HS256); although the later
is deprecated.

How ever your code seems to have a couple of missing things such as
LoginAuth Filters, LogoutFilters e.t.c. I am saying saw becoz I created an
exact copy of your program with small modifications but it just couldn't
work.

When I tried to sign up it would say ByCrypt password cannot be null even
though I had code encoding the password.

Secondly even after creating a username and password by other means I would
still not be able to log in, as the system would say no username found.

Kindly check my code from the below link if you don't mind:

https://github.com/omudzingwa/spring-security-jwt-redis-login-logout-demo

Regards,

Obert

**Comment by omudzingwa** [comment]
Hi.  I have made the change you recommended and compiled and its compiling but how ever when I try to signup I am getting the following message: 

Github Link: 

https://github.com/omudzingwa/Spring-Boot-Security-Jwt-Redis-Login-Logout-Demo01

java.lang.IllegalArgumentException: rawPassword cannot be null
	at org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder.encode(BCryptPasswordEncoder.java:107) ~[spring-security-crypto-6.2.1.jar:6.2.1]
	at com.quadrant.jwt.auth.AuthService.signUp(AuthService.java:46) ~[classes/:na]
	at com.quadrant.jwt.auth.AuthController.signup(AuthController.java:31) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:261) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:189) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.3.jar:6.1.3]

AND then when I try to login with a user that I created through some other means and there is user is indeed there with username: admin and  encrypted password: admin but am getting username not found.

Hibernate: 
    select
        u1_0.id,
        u1_0.firstname,
        u1_0.lastname,
        u1_0.password,
        u1_0.role,
        u1_0.username 
    from
        users u1_0 
    where
        u1_0.username is null
